name: music_hub
description: A music player made for Android.
publish_to: 'none'
version: 1.5.0+0

environment:
  sdk: ^3.10.0

dependencies:
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  get_it: ^9.1.1
  theme_provider: ^0.6.0
  animations: ^2.1.1
  font_awesome_flutter: ^11.0.0
  youtube_explode_dart: ^3.0.5
  dio: ^5.9.0
  flutter_media_metadata: ^1.0.0+1
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  audio_video_progress_bar: ^2.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dependency_overrides:
  flutter_media_metadata:
    path: plugins/flutter_media_metadata

dev_dependencies:
  # change_app_package_name: <=1.1.0
  # flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

import_sorter:
  comments: false
  # dart run import_sorter:main

# flutter_launcher_icons:
#   android: true
#   image_path: 'assets/images/icon.png'
#   min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
